import { CLINIC } from "./config";
import type { Booking, Prescription } from "../store/clinic";

function esc(s: string): string {
  return s.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] || c);
}

export function letterheadHtml(booking: Booking, rx: Prescription): string {
  return `<div class="rx">
    <header>
      <p class="clinic">${esc(CLINIC.name)}</p>
      <h1>${esc(CLINIC.doctor)}</h1>
      <p>${esc(CLINIC.credentials)} · ${esc(CLINIC.role)}</p>
      <p class="hi">${esc(CLINIC.hindi)}</p>
      <p class="addr">${esc(CLINIC.address)}</p>
      <p>${esc(CLINIC.phoneDisplay)} · ${esc(CLINIC.site)}</p>
    </header>
    <hr />
    <p><strong>Patient:</strong> ${esc(booking.firstName)} · ${esc(booking.phone)} · ${esc(booking.email)}</p>
    <p><strong>Visit:</strong> ${esc(booking.mode)} · ${esc(booking.dateIso)} ${esc(booking.time)} · ${esc(booking.reason)}</p>
    <h2>Findings</h2>
    <p>${esc(rx.findings || "—")}</p>
    <h2>Plan</h2>
    <p>${esc(rx.plan || "—")}</p>
    <h2>Medicines / procedures</h2>
    <p>${esc(rx.medicines || "—")}</p>
    <h2>Follow-up</h2>
    <p>${esc(rx.followUp || "—")}</p>
    <p class="sign">Sd/- ${esc(CLINIC.doctor)}<br/>${esc(CLINIC.credentials)}</p>
    <p class="muted">Written in the doctor's name on Shree Urocare letterhead. Not a Tej Kaya product prescription. This is not generated by the Ritual Finder.</p>
  </div>`;
}

export function letterheadStyles(): string {
  return `body{font-family:Georgia,serif;color:#161410;background:#fff;padding:1.5rem;max-width:42rem;margin:0 auto}
    .clinic{letter-spacing:.2em;text-transform:uppercase;font-size:.75rem;color:#8c7350}
    h1{font-size:1.5rem;font-weight:500;margin:.2rem 0}
    .hi{font-size:.95rem;color:#5a2c2c}
    .addr{font-size:.85rem;color:#3a342c}
    hr{border:0;border-top:1px solid #b8956a;margin:1rem 0}
    h2{font-size:1rem;margin:1.1rem 0 .3rem}
    .sign{margin-top:2rem}
    .muted{font-size:.75rem;color:#6e675c;margin-top:2rem}`;
}
